name: Update RSS

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  
concurrency:
  group: argos-update
  cancel-in-progress: true

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update RSS
        env:
          NTFY_SERVER: ${{ secrets.NTFY_SERVER }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: |
          python update_rss.py
          python update_podcasts.py
         
      - name: Commit RSS
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add argos_rss.xml argos_podcasts.xml last_seen.json
          git commit -m "Update ARGOS RSS" || exit 0
          git push
